### ISSUE TITLE
楼主，重大Bug

### ISSUE THREAD

**Issue by Dreamer206602** [blackCave/Retrofit_RxJava_MVP#1]
在使用搜索的功能时，如果id输入为1,图片数量输入也为1，会报空指针异常
![debug](https://cloud.githubusercontent.com/assets/14008096/16073246/9c397ca8-3317-11e6-912f-fda8db6d2754.png)

**Comment by 7449** [comment]
这个应该是几率性问题...空指针是弹回输入法时碰到的,我之前没有碰到过,而且刚才测试的时候这个bug死活都不出来。稍微改了一下，应该不会再报异常了。

**Comment by Dreamer206602** [comment]
好的，我再测试下
