### ISSUE TITLE
亲，有个问题请教一下？

### ISSUE THREAD

**Issue by thomasbnb** [blackCave/Retrofit_RxJava_MVP#2]
UIUtils.getActivity()
我如果在某个工具类中调用，返回的是哪个activity对象呢？

**Comment by 7449** [comment]
UIUtils.getActivity().getClass().getSimpleName()
这句话用log打印出来 ,打印出来的哪个Activity名字就是哪个Activity对象
你可以看看BaseActivity里面的Log.i

**Comment by thomasbnb** [comment]
在任何地方都能获得activity的引用，那这个activity是不是就内存泄漏了啊！

**Comment by 7449** [comment]
不会，系统会回收的,你可以打Log看下
