### ISSUE TITLE
xxxModelImpl中注册的Subscriber，什么时候unsubsribe ? 

### ISSUE THREAD

**Issue by yzbai** [blackCave/Retrofit_RxJava_MVP#3]
寻找RxJava例子看到这里，谢谢提供这么好的例子。
有个问题请教一下：
看到BaseActivity中Destroy的时候会调用unsubscribe()，但BaseActivity中的subscription成员一直没有赋值，而xxxModelImpl中注册的Subscriber，应该什么时候unsubscribe？

Fragment中同样。

**Comment by 7449** [comment]
BaseActivity 中 Destroy 的时候会调用 unsubscribe()
这里你可以认为并没有卵用，因为方法根本就没走进去，我只不过是刚开始学习时这样写了下，提醒下自己而已。
至于销毁，NetWorkRequest.java这个类
Network.getTngouApi().getNewsDetail(id)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(subscriber);
随便复制了个，看.subscribe(subscriber);这句源码。
最后调用了Subscriptions.unsubscribed();
如果你还是不放心可以在.observeOn(AndroidSchedulers.mainThread())之前加一句 .unsubscribeOn(Schedulers.io())

**Comment by yzbai** [comment]
@7449 源码里 Subscriptions.unsubscribed(); 的调用时在catch里，出异常了才调用的。

.unsubscribeOn(Schedulers.io()) 是指unsubscribe的时候使用的线程吧。应该还是要显示调用unsubscribe的。

**Comment by 7449** [comment]
@yzbai  
在. observeOn(AndroidSchedulers.mainThread()) 之前加一句 .unsubscribeOn()
这个你subscribeOn里面是哪个 就填哪个,之前那个try没看见，汗

**Comment by 7449** [comment]
@yzbai 我更新代码了，你看下NetWorkRequest.java 这个类，通过Log我得出的结论是如果不停的请求网络会执行subscription.unsubscribe();网络请求后RxJava会自动销毁，
