### ISSUE TITLE
Observable解绑问题

### ISSUE THREAD

**Issue by nwx546250** [blackCave/Retrofit_RxJava_MVP#4]
```
public static void newsDetail(int id, Subscriber<NewsDetailInfo> subscriber) {
    //当有两个请求的时候，第一个请求发送后数据数据还没返回的时候，第二个请求也发送，
    // 这个时候RxUtils.unsubscribe();就把第一个请求的订阅的对象解绑了，第一个请求就不能
    // 通过回调返回数据。我觉得应该在合适的地方进行解绑，比如activity 销毁的时候，把所有订阅的对象
    //全部解绑
    RxUtils.unsubscribe();
    RxUtils.subscription = Network.getTngouApi().getNewsDetail(id)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(subscriber);
}
```

你觉得呢？

**Comment by 7449** [comment]
这个Demo是年初的时候写的 距离现在也有段时间了，有一些地方确实有些问题，对于unsubscribe问题  可以使用这个https://github.com/trello/RxLifecycle.git 这个开源，至于销毁解绑  ，不能一股脑的全部解绑，例如很常见的viewpager+fragment，viewpager滑动会调用onDestroyView这个方法 如果这个时候解绑了 那页面就是一片空白  稍微好点的就是一个emptyView,
解绑要看你项目的结构了  ，在合适的地方去解绑。
还有个比较明显的问题是项目中的networkError();  这个用的rxbus，这样只要一个地方网络异常了  其余地方都会收到这个指令，为了方便一直都没有改。 @nwx546250
